# Generated by Django 4.2.20 on 2025-03-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_books_availale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='availale',
        ),
    ]
