# Generated by Django 4.2.20 on 2025-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_books_availale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishedYear',
            field=models.PositiveIntegerField(),
        ),
    ]
