# Generated by Django 4.2.20 on 2025-03-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_books_publishedyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishedYear',
            field=models.DateField(),
        ),
    ]
